import React, { useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { useAppStore } from '../../store';
import { cn } from '../../lib/utils';
import type { TabType } from '../../types/payloads';
import { PayloadsListView, TabNavigation } from './PayloadsListView';
import { CreatePayloadEmbed, CreateWrapperEmbed } from './CreatePayloadEmbed';
import { Box, Plus, Package } from 'lucide-react';
import { useReactiveVar } from "@apollo/client/react";
import { useQueryCompat as useQuery } from "../../lib/useQueryCompat";
import { PayloadsQuery } from '../../lib/api';
import { meState } from '../../lib/state';

const Payloads = () => {
    const isSidebarCollapsed = useAppStore(s => s.isSidebarCollapsed);
    const [searchParams, setSearchParams] = useSearchParams();
    const me = useReactiveVar(meState);
    
    // Get initial tab from URL or default to 'list'
    const initialTab = (searchParams.get('tab') as TabType) || 'list';
    const [activeTab, setActiveTab] = useState<TabType>(initialTab);
    const [totalPayloads, setTotalPayloads] = useState(0);

    // Query just for count
    useQuery<any>(PayloadsQuery, {
        variables: { offset: 0, limit: 1, showDeleted: false, showAutogenerated: false },
        fetchPolicy: "cache-and-network",
        onCompleted: (data: any) => {
            setTotalPayloads(data.payload_aggregate?.aggregate?.count || 0);
        }
    });

    const handleTabChange = (tab: TabType) => {
        setActiveTab(tab);
        setSearchParams({ tab });
    };

    const noOperation = (me?.user?.current_operation_id || 0) === 0;

    if (noOperation) {
        return (
            <div className="min-h-screen bg-void text-signal font-sans selection:bg-signal selection:text-void">
                <div className={cn("transition-all duration-300 p-6 lg:p-12 min-h-screen flex items-center justify-center", isSidebarCollapsed ? "ml-16" : "ml-64")}>
                    <div className="text-center">
                        <Box size={48} className="mx-auto mb-4 text-gray-500" />
                        <h1 className="text-xl font-bold text-gray-400 mb-2">No Operation Selected</h1>
                        <p className="text-gray-500">Please select an operation to view payloads</p>
                    </div>
                </div>
            </div>
        );
    }

    return (
        <div className="min-h-screen bg-void text-signal font-sans selection:bg-signal selection:text-void">
            <div className={cn("transition-all duration-300 p-6 lg:p-12 min-h-screen flex flex-col", isSidebarCollapsed ? "ml-16" : "ml-64")}>
                {/* Header - Changes based on active tab */}
                <header className="flex justify-between items-center mb-8 border-b border-ghost/30 pb-6">
                    <div className="flex items-center gap-4">
                        <div className="p-3 border border-white/50 bg-white/10 rounded">
                            {activeTab === 'list' ? (
                                <Box size={24} className="text-white" />
                            ) : activeTab === 'create' ? (
                                <Plus size={24} className="text-white" />
                            ) : (
                                <Package size={24} className="text-white" />
                            )}
                        </div>
                        <div>
                            <h1 className="text-2xl font-bold tracking-widest text-white uppercase">
                                {activeTab === 'list'
                                    ? 'PAYLOADS OVERVIEW'
                                    : activeTab === 'create'
                                        ? 'CREATE PAYLOAD'
                                        : 'CREATE WRAPPER'}
                            </h1>
                            <p className="text-xs text-gray-300 font-mono flex items-center gap-2 uppercase tracking-[0.2em]">
                                <span className="w-2 h-2 bg-signal rounded-full animate-pulse" />
                                {activeTab === 'list'
                                    ? 'PAYLOAD LIST'
                                    : activeTab === 'create'
                                        ? 'GENERATE PAYLOAD'
                                        : 'PAYLOAD WRAPPER'}
                            </p>
                        </div>
                    </div>

                    {/* Stats Summary - Only show on list tab */}
                    {activeTab === 'list' && (
                        <div className="flex gap-6 text-xs font-mono items-center">
                            <div className="text-right border-l border-ghost/20 pl-6">
                                <div className="text-gray-400">TOTAL_PAYLOADS</div>
                                <div className="text-xl text-signal">{totalPayloads}</div>
                            </div>
                        </div>
                    )}

                    {/* Generate Payload Button - Show on list tab */}
                    {activeTab === 'list' && (
                        <button
                            onClick={() => handleTabChange('create')}
                            className="flex items-center gap-2 px-4 py-2 border border-signal text-signal hover:bg-signal hover:text-void font-mono text-sm transition-colors rounded"
                        >
                            <Plus size={16} />
                            GENERATE PAYLOAD
                        </button>
                    )}
                </header>

                {/* Tab Navigation */}
                <TabNavigation 
                    activeTab={activeTab} 
                    onTabChange={handleTabChange}
                    totalPayloads={totalPayloads}
                />

                {/* Tab Content */}
                <AnimatePresence mode="wait">
                    {activeTab === 'list' && (
                        <motion.div
                            key="list"
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            exit={{ opacity: 0 }}
                            className="flex-1 flex flex-col overflow-hidden mt-6"
                        >
                            <PayloadsListView 
                                onSwitchToCreate={() => handleTabChange('create')}
                                onSwitchToWrapper={() => handleTabChange('wrapper')}
                            />
                        </motion.div>
                    )}
                    {activeTab === 'create' && (
                        <motion.div
                            key="create"
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            exit={{ opacity: 0 }}
                            className="flex-1 flex flex-col overflow-hidden mt-6"
                        >
                            <CreatePayloadEmbed onComplete={() => handleTabChange('list')} />
                        </motion.div>
                    )}
                    {activeTab === 'wrapper' && (
                        <motion.div
                            key="wrapper"
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1 }}
                            exit={{ opacity: 0 }}
                            className="flex-1 flex flex-col overflow-hidden mt-6"
                        >
                            <CreateWrapperEmbed onComplete={() => handleTabChange('list')} />
                        </motion.div>
                    )}
                </AnimatePresence>
            </div>
        </div>
    );
};

export default Payloads;
