import React, { useState, useEffect, useRef, useCallback } from 'react';
import { useSubscription, useMutation } from "@apollo/client/react";
import { useQueryCompat as useQuery, useLazyQueryCompat as useLazyQuery} from "../../lib/useQueryCompat";
import { AnimatePresence } from 'framer-motion';
import { Plus, Upload, Package, Eye, EyeOff, List, Loader2, Box } from 'lucide-react';
import { cn, b64DecodeUnicode, downloadBlob } from '../../lib/utils';
import { getSkewedNow } from '../../lib/time';
import { snackActions } from '../../lib/snackbar';
import { useBattleMode } from '../../context/BattleModeContext';
import { SUB_Payloads, GET_BUILDING_PAYLOADS } from '../../lib/api/payloads';
import type { Payload, TabType } from '../../types/payloads';
import { PayloadRow } from './PayloadRow';
import { ImportPayloadConfigDialog } from './dialogs';
import { useNavigate } from 'react-router-dom';
import { PayloadsQuery, exportPayloadConfigQuery, payloadsCallbackAlert, payloadsCallbackAllowed, payloadsDelete, rebuildPayloadMutation, restorePayloadMutation } from '../../lib/api';

const BUILD_POLL_INTERVAL_MS = 4_000;

export const TabNavigation: React.FC<{
    activeTab: TabType;
    onTabChange: (tab: TabType) => void;
    totalPayloads: number;
}> = ({ activeTab, onTabChange, totalPayloads }) => {
    const tabs = [
        { id: 'list' as TabType, label: 'PAYLOADS', icon: List, count: totalPayloads },
        { id: 'create' as TabType, label: 'CREATE PAYLOAD', icon: Plus },
        { id: 'wrapper' as TabType, label: 'CREATE WRAPPER', icon: Package },
    ];

    return (
        <div className="flex items-center gap-1 border-b border-ghost/30">
            {tabs.map((tab) => {
                const Icon = tab.icon;
                const isActive = activeTab === tab.id;
                return (
                    <button
                        key={tab.id}
                        onClick={() => onTabChange(tab.id)}
                        className={cn(
                            "flex items-center gap-2 px-4 py-3 border-b-2 transition-all font-mono text-sm",
                            isActive
                                ? "border-signal text-signal bg-signal/5"
                                : "border-transparent text-gray-400 hover:text-signal hover:bg-signal/5"
                        )}
                    >
                        <Icon size={16} />
                        {tab.label}
                        {tab.count !== undefined && (
                            <span className={cn(
                                "px-1.5 py-0.5 text-xs rounded",
                                isActive ? "bg-signal/20" : "bg-ghost/20"
                            )}>
                                {tab.count}
                            </span>
                        )}
                    </button>
                );
            })}
        </div>
    );
};

// ============================================
// Payloads List Component (extracted from main)
// ============================================

export const PayloadsListView: React.FC<{
    onSwitchToCreate: () => void;
    onSwitchToWrapper: () => void;
}> = ({ onSwitchToCreate, onSwitchToWrapper }) => {
    const navigate = useNavigate();
    const handleRebuildFromConfig = useCallback((payload: Payload) => {
        navigate('/create-payload/new', {
            state: {
                fromPayloadId: payload.id,
                fromPayloadOS: payload.os,
                fromPayloadType: payload.payloadtype.name,
            },
        });
    }, [navigate]);
    const { active: isCombat } = useBattleMode();
    const [fromNow] = useState((getSkewedNow()).toISOString());
    const [payloads, setPayloads] = useState<Payload[]>([]);
    const [showDeleted, setShowDeleted] = useState(false);
    const [showAutogenerated, setShowAutogenerated] = useState(false);
    const [loading, setLoading] = useState(true);
    const [showImportDialog, setShowImportDialog] = useState(false);
    const [pageData, setPageData] = useState({
        totalCount: 0,
        fetchLimit: 20,
        currentPage: 1
    });
    const mountedRef = useRef(true);
    // Item 2: track prior build phases to detect build-complete state changes
    const prevBuildPhases = useRef<Record<number, string>>({});

    // Item 6: lazy query to poll currently-building payloads that existed before mount
    const [fetchBuilding] = useLazyQuery<any>(GET_BUILDING_PAYLOADS, {
        fetchPolicy: 'network-only',
        onCompleted: (data: any) => {
            if (!mountedRef.current) return;
            if (!data.payload.length) return;
            setPayloads(prev => {
                const updated = [...prev];
                for (const bp of data.payload) {
                    const idx = updated.findIndex(p => p.id === bp.id);
                    if (idx > -1) updated[idx] = { ...bp };
                }
                return updated;
            });
        }
    });

    // Subscription for real-time updates
    useSubscription<any>(SUB_Payloads, {
        variables: { now: fromNow },
        fetchPolicy: "no-cache",
        onData: ({ data }: { data: any } ) => {
            if (!mountedRef.current) return;
            setPayloads(prev => {
                const updated = data.data.payload_stream.reduce((acc: Payload[], cur: Payload) => {
                    const index = acc.findIndex((p) => p.id === cur.id);
                    if (index > -1) {
                        acc[index] = { ...cur };
                        return [...acc];
                    }
                    return [cur, ...acc];
                }, [...prev]);
                updated.sort((a: Payload, b: Payload) => (a.id > b.id ? -1 : 1));
                return updated;
            });
        },
        onError: (err) => { console.error('[SUB_Payloads] subscription error:', err); },
    });

    // Initial query
    useQuery<any>(PayloadsQuery, {
        variables: { offset: 0, limit: pageData.fetchLimit, showDeleted: false, showAutogenerated: false },
        fetchPolicy: "no-cache",
        onCompleted: (data: any) => {
            setPageData(prev => ({ ...prev, totalCount: data.payload_aggregate.aggregate.count }));
            setPayloads(data.payload);
            setLoading(false);
        }
    });

    // Lazy query for pagination
    const [fetchNewPage] = useLazyQuery<any>(PayloadsQuery, {
        onCompleted: (data: any) => {
            snackActions.dismiss();
            setPageData(prev => ({ ...prev, totalCount: data.payload_aggregate.aggregate.count }));
            setPayloads(data.payload);
            setLoading(false);
        }
    });

    // Mutations
    const [deletePayload] = useMutation<any>(payloadsDelete, {
        onCompleted: (data: any) => {
            if (data.updatePayload.status === "success") {
                const updated = payloads.map(p => p.id === data.updatePayload.id ? { ...p, deleted: true } : p);
                setPayloads(updated);
                snackActions.success("Payload deleted");
            } else {
                snackActions.error(data.updatePayload.error);
            }
        },
        onError: () => snackActions.warning("Failed to delete payload")
    });

    const [restorePayload] = useMutation<any>(restorePayloadMutation, {
        onCompleted: (data: any) => {
            const updated = payloads.map(p => p.id === data.updatePayload.id ? { ...p, deleted: false } : p);
            setPayloads(updated);
            snackActions.success("Payload restored");
        },
        onError: () => snackActions.warning("Failed to restore payload")
    });

    const [toggleCallbackAlert] = useMutation<any>(payloadsCallbackAlert, {
        onCompleted: (data: any) => {
            const updated = payloads.map(p => p.id === data.updatePayload.id ? { ...p, callback_alert: data.updatePayload.callback_alert } : p);
            setPayloads(updated);
            snackActions.success(data.updatePayload.callback_alert ? "Callback alerts enabled" : "Callback alerts disabled");
        },
        onError: () => snackActions.warning("Failed to update callback alert")
    });

    const [toggleCallbackAllowed] = useMutation<any>(payloadsCallbackAllowed, {
        onCompleted: (data: any) => {
            const updated = payloads.map(p => p.id === data.updatePayload.id ? { ...p, callback_allowed: data.updatePayload.callback_allowed } : p);
            setPayloads(updated);
            snackActions.success(data.updatePayload.callback_allowed ? "Callbacks allowed" : "Callbacks blocked");
        },
        onError: () => snackActions.warning("Failed to update callback allowed")
    });

    const [rebuildPayload] = useMutation<any>(rebuildPayloadMutation, {
        onCompleted: (data: any) => {
            if (data.rebuild_payload.status === "success") {
                snackActions.success("Rebuild triggered");
            } else {
                snackActions.error("Failed to rebuild: " + data.rebuild_payload.error);
            }
        },
        onError: (error) => snackActions.error("Failed to trigger rebuild: " + error.message)
    });

    const [exportConfig] = useLazyQuery<any>(exportPayloadConfigQuery, {
        fetchPolicy: "no-cache",
        onCompleted: (data: any) => {
            if (data.exportPayloadConfig.status === "success") {
                const dataBlob = new Blob([data.exportPayloadConfig.config], { type: 'text/plain' });
                downloadBlob(dataBlob, 'payload_config.json');
            } else {
                snackActions.error("Failed to export: " + data.exportPayloadConfig.error);
            }
        },
        onError: (error) => snackActions.error("Failed to export: " + error.message)
    });

    // Handlers
    const handleChangePage = (page: number) => {
        setLoading(true);
        setPageData(prev => ({ ...prev, currentPage: page }));
        fetchNewPage({ 
            variables: { 
                offset: (page - 1) * pageData.fetchLimit, 
                limit: pageData.fetchLimit, 
                showDeleted, 
                showAutogenerated 
            }
        });
    };

    const handleToggleDeleted = () => {
        setShowDeleted(!showDeleted);
        setLoading(true);
        fetchNewPage({ 
            variables: { 
                offset: 0, 
                limit: pageData.fetchLimit, 
                showDeleted: !showDeleted, 
                showAutogenerated 
            }
        });
    };

    const handleToggleAutogenerated = () => {
        setShowAutogenerated(!showAutogenerated);
        setLoading(true);
        fetchNewPage({ 
            variables: { 
                offset: 0, 
                limit: pageData.fetchLimit, 
                showDeleted, 
                showAutogenerated: !showAutogenerated 
            }
        });
    };

    useEffect(() => {
        return () => { mountedRef.current = false; };
    }, []);

    // Item 2: toast notification when a build transitions from building → done
    useEffect(() => {
        for (const p of payloads) {
            const prev = prevBuildPhases.current[p.id];
            if (prev === 'building' && p.build_phase === 'success') {
                const fname = p.filemetum ? b64DecodeUnicode(p.filemetum.filename_text) : p.uuid.slice(0, 8);
                snackActions.success(`Build complete: ${fname}`);
            } else if (prev === 'building' && p.build_phase === 'error') {
                const fname = p.filemetum ? b64DecodeUnicode(p.filemetum.filename_text) : p.uuid.slice(0, 8);
                snackActions.error(`Build failed: ${fname}`);
            }
            prevBuildPhases.current[p.id] = p.build_phase;
        }
    }, [payloads]); // eslint-disable-line react-hooks/exhaustive-deps

    // Item 6: poll for pre-existing building payloads (subscription cursor starts at mount, misses prior builds)
    const hasBuildingPayloads = payloads.some(p => p.build_phase === 'building');
    useEffect(() => {
        if (!hasBuildingPayloads) return;
        fetchBuilding();
        const id = setInterval(() => { if (mountedRef.current) fetchBuilding(); }, BUILD_POLL_INTERVAL_MS);
        return () => clearInterval(id);
    }, [hasBuildingPayloads]); // eslint-disable-line react-hooks/exhaustive-deps

    const totalPages = Math.ceil(pageData.totalCount / pageData.fetchLimit);

    return (
        <div className="flex-1 flex flex-col min-w-0 overflow-hidden">
            {/* Toolbar */}
            <div className="flex items-center justify-between mb-4">
                <div className="flex items-center gap-3">
                    <button
                        onClick={handleToggleDeleted}
                        className={cn(
                            "flex items-center gap-2 px-3 py-1.5 text-sm rounded border transition-colors",
                            showDeleted
                                ? "border-signal/50 text-signal bg-signal/10"
                                : "border-ghost/30 text-gray-400 hover:text-signal hover:border-signal/30"
                        )}
                    >
                        {showDeleted ? <Eye size={14} /> : <EyeOff size={14} />}
                        {showDeleted ? 'Showing Deleted' : 'Hide Deleted'}
                    </button>
                    <button
                        onClick={handleToggleAutogenerated}
                        className={cn(
                            "flex items-center gap-2 px-3 py-1.5 text-sm rounded border transition-colors",
                            showAutogenerated
                                ? "border-signal/50 text-signal bg-signal/10"
                                : "border-ghost/30 text-gray-400 hover:text-signal hover:border-signal/30"
                        )}
                    >
                        {showAutogenerated ? <Eye size={14} /> : <EyeOff size={14} />}
                        {showAutogenerated ? 'Showing Auto' : 'Hide Auto'}
                    </button>
                </div>
                <div className="flex items-center gap-2">
                    <button
                        onClick={() => setShowImportDialog(true)}
                        className={cn(
                            "flex items-center gap-2 px-3 py-1.5 text-sm rounded border transition-colors",
                            "border-ghost/30 text-gray-400 hover:text-signal hover:border-signal/30"
                        )}
                    >
                        <Upload size={14} />
                        Import Config
                    </button>
                    <button
                        onClick={onSwitchToCreate}
                        className="flex items-center gap-2 px-4 py-2 bg-signal hover:bg-signal/80 text-void font-medium rounded transition-colors text-sm"
                    >
                        <Plus size={16} />
                        New Payload
                    </button>
                    <button
                        onClick={onSwitchToWrapper}
                        className="flex items-center gap-2 px-4 py-2 bg-signal/10 hover:bg-signal/20 border border-signal/30 text-signal rounded transition-colors text-sm"
                    >
                        <Package size={16} />
                        Wrapper
                    </button>
                </div>
            </div>

            {/* Table */}
            <div className="flex-1 overflow-auto">
                {loading ? (
                    <div className="flex items-center justify-center h-64">
                        <Loader2 size={32} className="text-signal animate-spin" />
                    </div>
                ) : payloads.length === 0 ? (
                    <div className="flex flex-col items-center justify-center h-64 text-gray-500">
                        <Box size={48} className="mb-4" />
                        <p className="text-lg">No payloads found</p>
                        <button
                            onClick={onSwitchToCreate}
                            className="mt-4 flex items-center gap-2 px-4 py-2 bg-signal/10 hover:bg-signal/20 border border-signal/30 text-signal rounded transition-colors"
                        >
                            <Plus size={16} />
                            Create your first payload
                        </button>
                    </div>
                ) : (
                    <div className="border border-gray-800 rounded-lg overflow-hidden">
                        <table className="w-full">
                            <thead>
                                <tr className="border-b border-gray-700 bg-black/30">
                                    <th className="px-4 py-3 text-left text-xs text-gray-500 font-medium uppercase tracking-wider w-20"></th>
                                    <th className="px-4 py-3 text-left text-xs text-gray-500 font-medium uppercase tracking-wider">Agent</th>
                                    <th className="px-4 py-3 text-left text-xs text-gray-500 font-medium uppercase tracking-wider">File</th>
                                    <th className="px-4 py-3 text-left text-xs text-gray-500 font-medium uppercase tracking-wider">Progress</th>
                                    <th className="px-4 py-3 text-left text-xs text-gray-500 font-medium uppercase tracking-wider">Description</th>
                                    <th className="px-4 py-3 text-left text-xs text-gray-500 font-medium uppercase tracking-wider">C2 Status</th>
                                    <th className="px-4 py-3 text-left text-xs text-gray-500 font-medium uppercase tracking-wider">Tags</th>
                                </tr>
                            </thead>
                            <tbody>
                                <AnimatePresence>
                                    {payloads.map((payload) => (
                                        <PayloadRow
                                            key={payload.id}
                                            payload={payload}
                                            onDelete={(uuid) => deletePayload({ variables: { payload_uuid: uuid } })}
                                            onRestore={(uuid) => restorePayload({ variables: { payload_uuid: uuid } })}
                                            onToggleAlert={(uuid, alert) => toggleCallbackAlert({ variables: { payload_uuid: uuid, callback_alert: alert } })}
                                            onToggleAllowed={(uuid, allowed) => toggleCallbackAllowed({ variables: { payload_uuid: uuid, callback_allowed: allowed } })}
                                            onRebuild={(uuid) => rebuildPayload({ variables: { uuid } })}
                                            onRebuildFromConfig={handleRebuildFromConfig}
                                            onExportConfig={(uuid) => exportConfig({ variables: { uuid } })}
                                            showDeleted={showDeleted}
                                            isCombat={isCombat}
                                            onTagsUpdated={() => fetchNewPage({ variables: { offset: (pageData.currentPage - 1) * pageData.fetchLimit, limit: pageData.fetchLimit, showDeleted, showAutogenerated } })}
                                        />
                                    ))}
                                </AnimatePresence>
                            </tbody>
                        </table>
                    </div>
                )}
            </div>

            {/* Pagination */}
            {totalPages > 1 && (
                <div className="border-t border-ghost/30 pt-4 mt-4 flex items-center justify-between gap-2">
                    {/* Per-page selector — Item 7 */}
                    <div className="flex items-center gap-2 text-xs font-mono">
                        <span className="text-ghost/50">Per page:</span>
                        {[20, 50, 100].map(n => (
                            <button
                                key={n}
                                onClick={() => {
                                    setPageData(prev => ({ ...prev, fetchLimit: n, currentPage: 1 }));
                                    setLoading(true);
                                    fetchNewPage({ variables: { offset: 0, limit: n, showDeleted, showAutogenerated } });
                                }}
                                className={cn(
                                    "px-2 py-0.5 rounded border transition-colors",
                                    pageData.fetchLimit === n
                                        ? "border-signal bg-signal/10 text-signal"
                                        : "border-ghost/30 text-ghost hover:text-signal hover:border-signal/30"
                                )}
                            >
                                {n}
                            </button>
                        ))}
                    </div>

                    {/* Page nav */}
                    <div className="flex items-center gap-2">
                        <button
                            onClick={() => handleChangePage(1)}
                            disabled={pageData.currentPage === 1}
                            className="px-3 py-1.5 rounded border border-ghost/30 text-gray-400 hover:text-signal hover:border-signal/30 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                        >
                            First
                        </button>
                        <button
                            onClick={() => handleChangePage(pageData.currentPage - 1)}
                            disabled={pageData.currentPage === 1}
                            className="px-3 py-1.5 rounded border border-ghost/30 text-gray-400 hover:text-signal hover:border-signal/30 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                        >
                            Prev
                        </button>
                        <span className="px-4 text-gray-400 font-mono text-sm">
                            Page {pageData.currentPage} of {totalPages}
                            <span className="ml-2 text-ghost/40 text-xs">({pageData.totalCount} total)</span>
                        </span>
                        <button
                            onClick={() => handleChangePage(pageData.currentPage + 1)}
                            disabled={pageData.currentPage === totalPages}
                            className="px-3 py-1.5 rounded border border-ghost/30 text-gray-400 hover:text-signal hover:border-signal/30 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                        >
                            Next
                        </button>
                        <button
                            onClick={() => handleChangePage(totalPages)}
                            disabled={pageData.currentPage === totalPages}
                            className="px-3 py-1.5 rounded border border-ghost/30 text-gray-400 hover:text-signal hover:border-signal/30 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                        >
                            Last
                        </button>
                    </div>
                </div>
            )}
            
            {/* Import Payload Config Dialog */}
            <ImportPayloadConfigDialog
                open={showImportDialog}
                onClose={() => setShowImportDialog(false)}
            />
        </div>
    );
};

// ============================================
// OS Info Helper
// ============================================
