import { gql } from '@apollo/client';

export const payloadFragment = gql`
fragment payloadData on payload {
  build_message
  build_phase
  build_stderr
  build_stdout
  callback_alert
  callback_allowed
  id
  uuid
  description
  deleted
  auto_generated
  timestamp
  payload_type_semver
  os
  creation_time
  payloadtype {
    id
    name
    semver
  }
  operator {
    id
    username
  }
  payload_build_steps(order_by: {step_number: asc}) {
    step_name
    step_number
    step_success
    step_skip
    start_time
    end_time
    step_stdout
    step_stderr
    step_description
    id
  }
  buildparameterinstances {
    id
    value
    enc_key_base64
    dec_key_base64
    buildparameter {
      id
      name
      description
      parameter_type
    }
  }
  payloadcommands {
    id
    version
    command {
      id
      cmd
      version
    }
  }
  tags {
    tagtype {
        name
        color
        id
      }
    id
  }
  filemetum {
    agent_file_id
    filename_text
    id
    md5
    sha1
    size
    tags {
        tagtype {
            name
            color
            id
          }
        id
    }
  }
  payloadc2profiles {
    c2profile {
      running
      name
      is_p2p
      container_running
    }
  }
  c2profileparametersinstances(order_by: {c2profile: {name: asc}}) {
    value
    enc_key_base64
    dec_key_base64
    c2profile { name }
    c2profileparameter { name parameter_type }
  }
  operator {
    id
    username
  }
  task {
    display_id
  }
  wrapped_payload_id
  payload {
    payloadtype { name }
    payloadc2profiles {
      c2profile {
        running
        name
        is_p2p
        container_running
      }
    }
    c2profileparametersinstances(order_by: {c2profile: {name: asc}}) {
      value
      c2profile { name }
      c2profileparameter { name parameter_type }
    }
  }
  eventstepinstance {
    eventgroupinstance {
      id
      eventgroup {
        id
        name
      }
    }
    eventstep {
      name
    }
  }
}
`;

export const SUB_Payloads = gql`
${payloadFragment}
subscription SubPayloadsQuery($now: timestamp!) {
  payload_stream(batch_size: 10, cursor: {initial_value: {timestamp: $now}, ordering: ASC}) {
    ...payloadData
  }
}
`;

// Item 6: fetch currently-building payloads (subscription cursor misses pre-existing builds)
export const GET_BUILDING_PAYLOADS = gql`
${payloadFragment}
query GetBuildingPayloads {
  payload(where: {build_phase: {_eq: "building"}}) {
    ...payloadData
  }
}
`;

export const PayloadsQuery = gql`
${payloadFragment}
query PayloadsQuery($offset: Int!, $limit: Int!, $showDeleted: Boolean!, $showAutogenerated: Boolean!) {
  payload(order_by: {id: desc}, offset: $offset, limit: $limit, where: {auto_generated: {_eq: $showAutogenerated}, deleted: {_eq: $showDeleted}}) {
    ...payloadData
  }
  payload_aggregate(where: {auto_generated: {_eq: $showAutogenerated}, deleted: {_eq: $showDeleted}}) {
    aggregate {
      count
    }
  }
}
`;

export const payloadsDelete = gql`
mutation PayloadsDeletePayloadMutation($payload_uuid: String!) {
  updatePayload(payload_uuid: $payload_uuid, deleted: true) {
      status
      error
      id
      deleted
  }
}
`;

export const payloadsCallbackAlert = gql`
mutation PayloadsCallbackAlertMutation($payload_uuid: String!, $callback_alert: Boolean!) {
  updatePayload(callback_alert: $callback_alert, payload_uuid: $payload_uuid) {
    id
    callback_alert
    status
    error
  }
}
`;

export const restorePayloadMutation = gql`
mutation RestorePayloadToUndeleted($payload_uuid: String!){
  updatePayload(deleted: false, payload_uuid: $payload_uuid) {
    id
    deleted
    status
    error
  }
}
`;

export const payloadsCallbackAllowed = gql`
mutation PayloadsCallbackAllowedMutation($payload_uuid: String!, $callback_allowed: Boolean!) {
  updatePayload(callback_allowed: $callback_allowed, payload_uuid: $payload_uuid) {
    id
    callback_allowed
    status
    error
  }
}
`;

export const rebuildPayloadMutation = gql`
mutation triggerRebuildMutation($uuid: String!) {
  rebuild_payload(uuid: $uuid) {
      status
      error
      uuid
  }
}
`;

export const exportPayloadConfigQuery = gql`
query exportPayloadConfigQuery($uuid: String!) {
  exportPayloadConfig(uuid: $uuid) {
      status
      error
      config
  }
}
`;

// Update filename mutation
export const updateFilenameMutation = gql`
mutation updateFilename($file_id: Int!, $filename: bytea!) {
  update_filemeta_by_pk(pk_columns: {id: $file_id}, _set: {filename: $filename}) {
    filename_text
    id
  }
}
`;

// Update description mutation
export const updatePayloadDescriptionMutation = gql`
mutation updatePayloadDescription($payload_uuid: String!, $description: String) {
  updatePayload(payload_uuid: $payload_uuid, description: $description) {
    description
    id
  }
}
`;

// Generate redirect rules query
export const generateRedirectRulesQuery = gql`
query generateRedirectRules($uuid: String!) {
  redirect_rules(uuid: $uuid) {
    status
    error
    output
  }
}
`;

// Check agent configuration query
export const checkAgentConfigQuery = gql`
query checkAgentConfig($uuid: String!) {
  config_check(uuid: $uuid) {
    status
    error
    output
  }
}
`;

// Generate IOCs query
export const generateIOCsQuery = gql`
query generateIOCs($uuid: String!) {
  c2GetIOC(uuid: $uuid) {
    status
    error
    output
  }
}
`;

// Generate sample message query
export const generateSampleMessageQuery = gql`
query generateSampleMessage($uuid: String!) {
  c2SampleMessage(uuid: $uuid) {
    status
    error
    output
  }
}
`;

// Import payload config mutation (reuse createPayload)
export const importPayloadMutation = gql`
mutation importPayloadConfig($payload: String!) {
  createPayload(payloadDefinition: $payload) {
    error
    status
    uuid
  }
}
`;

// Host file mutation
export const hostFileMutation = gql`
mutation hostFileMutation($c2_id: Int!, $file_uuid: String!, $host_url: String!, $alert_on_download: Boolean, $remove: Boolean) {
  c2HostFile(c2_id: $c2_id, file_uuid: $file_uuid, host_url: $host_url, alert_on_download: $alert_on_download, remove: $remove) {
    status
    error
  }
}
`;

// Get running C2 profiles for host file
export const getRunningC2ProfilesQuery = gql`
query getRunningC2Profiles {
  c2profile(where: {deleted: {_eq: false}, container_running: {_eq: true}, is_p2p: {_eq: false}}, order_by: {name: asc}) {
    id
    name
  }
}
`;

// Get all payloads for compare dropdown
export const getPayloadsListQuery = gql`
query GetPayloadsList {
  payload(where: {deleted: {_eq: false}}, order_by: {id: desc}) {
    id
    uuid
    description
    payloadtype { name }
    filemetum { filename_text }
  }
}
`;

// Get payload full details for compare/detail view
export const getPayloadFullDetailsQuery = gql`
query GetPayloadFullDetails($payload_id: Int!) {
  payload(where: {id: {_eq: $payload_id}}) {
    uuid
    callback_allowed
    payloadtype { name }
    operator { username }
    creation_time
    os
    description
    payloadcommands {
      id
      version
      command { cmd id version }
    }
    wrapped_payload_id
    payload {
      payloadtype { name }
      payloadc2profiles {
        c2profile { running name is_p2p container_running }
      }
      c2profileparametersinstances(order_by: {c2profile: {name: asc}}) {
        value
        c2profile { name }
        c2profileparameter { name parameter_type }
      }
    }
    eventstepinstance {
      eventgroupinstance {
        id
        eventgroup { id name }
      }
      eventstep { name }
    }
    filemetum { filename_text agent_file_id id md5 sha1 size }
    payload_build_steps(order_by: {step_number: asc}) {
      step_name step_number step_success step_stdout step_stderr step_skip step_description start_time end_time id
    }
    buildparameterinstances {
      value id enc_key_base64 dec_key_base64
      buildparameter { description parameter_type name }
    }
    c2profileparametersinstances(order_by: {c2profile: {name: asc}}) {
      value count enc_key_base64 dec_key_base64
      c2profileparameter { description parameter_type name }
      c2profile { name }
    }
  }
}
`;

// Get commands for add/remove
export const getCommandsForPayloadQuery = gql`
query GetCommandsForPayload($uuid: String!) {
  payloadcommand(where: {payload: {uuid: {_eq: $uuid}}}) {
    command { cmd id }
    id
  }
  command(where: {deleted: {_eq: false}, payloadtype: {payloads: {uuid: {_eq: $uuid}}}}) {
    cmd id
  }
}
`;

export const addCommandMutation = gql`
mutation addCommand($command_id: Int!, $payload_id: Int!) {
  insert_payloadcommand_one(object: {command_id: $command_id, payload_id: $payload_id}) {
    id
    command { cmd }
  }
}
`;

export const removeCommandMutation = gql`
mutation removeCommand($command_id: Int!, $payload_id: Int!) {
  delete_payloadcommand(where: {command_id: {_eq: $command_id}, payload_id: {_eq: $payload_id}}) {
    returning { command { cmd } }
  }
}
`;

// Tag mutations
export const addTagToPayloadMutation = gql`
mutation addTagToPayload($payload_id: Int!, $tagtype_id: Int!) {
  insert_tag_one(object: {payload_id: $payload_id, tagtype_id: $tagtype_id}) {
    id
    tagtype { name color id }
  }
}
`;

export const removeTagFromPayloadMutation = gql`
mutation removeTagFromPayload($tag_id: Int!) {
  delete_tag_by_pk(id: $tag_id) { id }
}
`;

export const getTagTypesQuery = gql`
query getTagTypes {
  tagtype(where: {deleted: {_eq: false}}, order_by: {name: asc}) {
    id name color
  }
}
`;

// Create fake callback mutation
export const createFakeCallbackMutation = gql`
mutation createFakeCallback($payloadUUID: String!) {
    createFakeCallback(payloadUUID: $payloadUUID){
        status
        error
    }
}
`;

// Manually create callback with full config
export const createManualCallbackMutation = gql`
mutation createNewCallback($payloadUuid: String!, $callbackConfig: newCallbackConfig) {
  createCallback(payloadUuid: $payloadUuid, newCallback: $callbackConfig){
    status
    error
  }
}
`;

export const GET_PAYLOAD_TYPES = gql`
query getPayloadTypesQuery {
  payloadtype(where: {deleted: {_eq: false}, wrapper: {_eq: false}, agent_type: {_in: ["agent", "service"]}}) {
    id
    supported_os
    name
    note
    semver
    container_running
    author
    buildparameters(where: {deleted: {_eq: false}}, order_by: {ui_position: asc}) {
        id
        name
        description
        parameter_type
        default_value
        required
        choices
        group_name
        verifier_regex
    }
    payloadtypec2profiles {
        c2profile {
            name
            id
            description
            running
            container_running
            is_p2p
            c2profileparameters(where: {deleted: {_eq: false}}) {
                id
                name
                description
                parameter_type
                default_value
                required
                choices
                format_string
                randomize
            }
        }
    }
    commands(where: {deleted: {_eq: false}}, order_by: {cmd: asc}) {
        id
        cmd
        description
        help_cmd
        needs_admin
        attributes
    }
  }
}
`;

export const CREATE_PAYLOAD = gql`
mutation createPayload($payload: String!) {
    createPayload(payloadDefinition: $payload) {
        error
        status
        uuid
    }
}
`;
