import { gql } from '@apollo/client';

export const GET_PAYLOAD_TYPES = gql`
query getPayloadTypesQuery {
  payloadtype(where: {deleted: {_eq: false}, wrapper: {_eq: false}, agent_type: {_in: ["agent", "service"]}}) {
    id
    supported_os
    name
    note
    semver
    payloadtypec2profiles{
        c2profile{
            name
        }
    }
  }
}
`;

export const PAYLOAD_FRAGMENT = gql`
fragment payloadData on payload {
    id
    uuid
    description
    deleted
    auto_generated
    build_phase
    build_message
    build_stderr
    build_stdout
    creation_time
    callback_allowed
    callback_alert
    wrapped_payload_id
    operator {
      username
    }
    payload_type_semver
    payloadtype {
      id
      name
      semver
    }
    filemetum {
      agent_file_id
      filename_text
      id
      size
      md5
      sha1
    }
    payloadc2profiles {
      c2profile {
        running
        name
        is_p2p
        container_running
      }
    }
    buildparameterinstances {
        value
        buildparameter {
            name
            description
        }
    }
    payloadcommands {
      command {
        cmd
      }
    }
    payload_build_steps(order_by: {step_number: asc}) {
      step_name
      step_number
      step_success
      step_stdout
      step_stderr
      step_skip
      start_time
      end_time
    }
    os
}
`;

export const PAYLOAD_SUBSCRIPTION = gql`
${PAYLOAD_FRAGMENT}
subscription SubPayloadsQuery($now: timestamp!) {
  payload_stream(batch_size: 10, cursor: {initial_value: {timestamp: $now}, ordering: ASC}) {
    ...payloadData
  }
}
`;

export const GET_PAYLOADS_LIST = gql`
${PAYLOAD_FRAGMENT}
query PayloadsQuery($offset: Int!, $limit: Int!, $showDeleted: Boolean!, $showAutogenerated: Boolean!) {
  payload(order_by: {id: desc}, offset: $offset, limit: $limit, where: {auto_generated: {_eq: $showAutogenerated}, deleted: {_eq: $showDeleted}}) {
    ...payloadData
  }
  payload_aggregate(where: {auto_generated: {_eq: $showAutogenerated}, deleted: {_eq: $showDeleted}}) {
    aggregate {
      count
    }
  }
}
`;

export const GET_DASHBOARD_DATA = gql`
query GetMinervaDashboard($operator_id: Int!) {
  # 1. Active Callbacks
  callback(order_by: {id: asc}, where: {active: {_eq: true}}) {
    id
    display_id
    user
    host
    ip
    integrity_level
    last_checkin
    description
    payload {
        payloadtype {
            name
        }
    }
  }
  
  # 2. Recent Payloads
  payload(order_by: {id: desc}, limit: 5, where: {deleted: {_eq: false}, auto_generated: {_eq: false}}) {
    id
    uuid
    build_phase
    filemetum {
      filename_text
    }
    payloadtype {
      name
    }
  }

  # 3. Operations Status
  operation(where: {complete: {_eq: false}, deleted: {_eq: false}}) {
    id
    name
    complete
    members {
        username
    }
  }

  # 4. Recent Tasks / Command Stats (Simplified)
  task(limit: 20, order_by: {id: desc}) {
    id
    command_name
    status
    status_timestamp_preprocessing 
    operator {
        username
    }
  }
  
  # 5. Current Operator Info
  operator(where: {id: {_eq: $operator_id}}){ 
    username
    admin
  }

  # 6. C2 Profiles Status
  c2profile(where: {deleted: {_eq: false}}, order_by: {name: asc}) {
    id
    name
    running
    container_running
    is_p2p
    description
    author
    semver
    payloadtypec2profiles {
      payloadtype {
        name
      }
    }
  }
}
`;

export const GET_CALLBACKS = gql`
query GetCallbacks($limit: Int = 50, $offset: Int = 0) {
  callback(order_by: {id: desc}, limit: $limit, offset: $offset, where: {active: {_eq: true}}) {
    id
    display_id
    user
    host
    pid
    ip
    domain
    os
    architecture
    integrity_level
    last_checkin
    init_callback
    description
    payload {
      payloadtype {
        name
      }
    }
  }
}
`;

// --- New Queries for Payload Creation ---

export const GET_BUILD_PARAMETERS = gql`
query getPayloadTypesBuildParametersQuery($payloadtype: String!) {
  payloadtype(where: {name: {_eq: $payloadtype}}) {
    name
    id
    file_extension
    agent_type
    note
    supports_dynamic_loading
    supports_multiple_c2_in_build
    supports_multiple_c2_instances_in_build
    c2_parameter_deviations
    semver
    buildparameters(where: {deleted: {_eq: false} }, order_by: {description: asc}) {
        default_value
        description
        format_string
        id
        name
        parameter_type
        randomize
        required
        verifier_regex
        choices
        group_name
        supported_os
        hide_conditions
        ui_position
        dynamic_query_function
    }
  }
}
`;

export const GET_COMMANDS = gql`
query getCommands($payloadType: String!) {
  command(where: {payloadtype: {name: {_eq: $payloadType}}, deleted: {_eq: false}}, order_by: {cmd: asc}) {
    cmd
    attributes
    id
    supported_ui_features
    help_cmd
    description
    needs_admin
  }
}
`;

export const GET_C2_PROFILES = gql`
query getPayloadTypesC2ProfilesQuery($payloadType: String!, $operation_id: Int!) {
  c2profile(where: {payloadtypec2profiles: {payloadtype: {name: {_eq: $payloadType}}}, deleted: {_eq: false}}) {
    name
    is_p2p
    description
    id
    c2profileparameters(where: {deleted: {_eq: false}}) {
      default_value
      description
      format_string
      id
      name
      parameter_type
      randomize
      required
      verifier_regex
      choices
    }
    c2profileparametersinstances(where: {instance_name: {_is_null: false}, operation_id: {_eq: $operation_id}}, distinct_on: instance_name, order_by: {instance_name: asc}){
        instance_name
        id
    }
  }
}
`;

export const CREATE_PAYLOAD_MUTATION = gql`
 mutation createPayloadMutation($payload: String!) {
  createPayload(payloadDefinition: $payload) {
    error
    status
    uuid
  }
}
`;

export const GET_DYNAMIC_BUILD_PARAMS = gql`
mutation getDynamicBuildParamsMutation($payload_type: String!, $parameter_name: String!, $selected_os: String!){
    dynamicQueryBuildParameterFunction(payload_type: $payload_type, parameter_name: $parameter_name, selected_os: $selected_os){
        status
        error
        choices
        parameter_name
    }
}
`;

// --- Actions Mutations ---

export const REBUILD_PAYLOAD_MUTATION = gql`
mutation triggerRebuildMutation($uuid: String!) {
  rebuild_payload(uuid: $uuid) {
      status
      error
      uuid
  }
}
`;

// Using custom updatePayload resolver instead of direct table update
export const TOGGLE_PAYLOAD_DELETE_MUTATION = gql`
mutation togglePayloadDeleteStatus($payload_uuid: String!, $deleted: Boolean!) {
  updatePayload(payload_uuid: $payload_uuid, deleted: $deleted) {
    status
    error
    id
    deleted
  }
}
`;

export const UPDATE_FILENAME_MUTATION = gql`
mutation updateFilename($file_id: Int!, $filename: String!) {
  update_filemeta(where: {id: {_eq: $file_id}}, _set: {filename_text: $filename}) {
    returning {
        id
        filename_text
    }
  }
}
`;

export const EXPORT_PAYLOAD_CONFIG = gql`
query exportPayloadConfigQuery($uuid: String!) {
  exportPayloadConfig(uuid: $uuid) {
      status
      error
      config
  }
}
`;

export const UPDATE_PAYLOAD_DESCRIPTION = gql`
mutation updatePayloadDescription($payload_uuid: String!, $description: String!) {
  updatePayload(payload_uuid: $payload_uuid, description: $description) {
    status
    error
    id
    description
  }
}
`;

export const UPDATE_PAYLOAD_ALERTS = gql`
mutation updatePayloadAlerts($payload_uuid: String!, $callback_alert: Boolean!) {
  updatePayload(payload_uuid: $payload_uuid, callback_alert: $callback_alert) {
    status
    error
    id
    callback_alert
  }
}
`;

export const UPDATE_PAYLOAD_ALLOWED = gql`
mutation updatePayloadAllowed($payload_uuid: String!, $callback_allowed: Boolean!) {
  updatePayload(payload_uuid: $payload_uuid, callback_allowed: $callback_allowed) {
    status
    error
    id
    callback_allowed
  }
}
`;

export const GENERATE_REDIRECT_RULES = gql`
query generateRedirectRules($uuid: String!) {
  redirect_rules(uuid: $uuid) {
    status
    error
    output
  }
}
`;

export const CHECK_PAYLOAD_CONFIGURATION = gql`
query checkPayloadConfiguration($uuid: String!) {
  config_check(uuid: $uuid) {
    status
    error
    output
  }
}
`;

export const GENERATE_IOC = gql`
query generateIOC($uuid: String!) {
  c2GetIOC(uuid: $uuid) {
    status
    error
    output
  }
}
`;

export const GENERATE_SAMPLE_MESSAGE = gql`
query generateSampleMessage($uuid: String!) {
  c2SampleMessage(uuid: $uuid) {
    status
    error
    output
  }
}
`;
